import tabletsImg from "@/assets/p-tablets.jpg";
import syrupImg from "@/assets/p-syrup.jpg";
import vitaminImg from "@/assets/p-vitamin.jpg";
import facewashImg from "@/assets/p-facewash.jpg";
import sunscreenImg from "@/assets/p-sunscreen.jpg";
import serumImg from "@/assets/p-serum.jpg";
import moisturizerImg from "@/assets/p-moisturizer.jpg";
import shampooImg from "@/assets/p-shampoo.jpg";
import lipbalmImg from "@/assets/p-lipbalm.jpg";
import hairoilImg from "@/assets/p-hairoil.jpg";
import multivitaminImg from "@/assets/p-multivitamin.jpg";
import coughImg from "@/assets/p-cough.jpg";

export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  image: string;
  badge?: string;
  description: string;
  benefits: string[];
};

export const products: Product[] = [
  {
    id: "dolo-650",
    name: "Dolo 650 Tablet",
    brand: "Micro Labs",
    category: "Medicines",
    price: 32,
    mrp: 35,
    rating: 4.8,
    reviews: 1284,
    image:
      "https://www.medstown.com/wp-content/uploads/2025/06/dolo-650-paracetamol-tablets-1000x1000-1.webp",
    badge: "Trending",
    description: "Effective relief from fever and mild to moderate pain. Strip of 15 tablets.",
    benefits: ["Fast acting", "Doctor recommended", "Trusted formula"],
  },
  {
    id: "crocin",
    name: "Crocin Advance Tablet",
    brand: "GSK",
    category: "Medicines",
    price: 45,
    mrp: 52,
    rating: 4.7,
    reviews: 982,
    image: tabletsImg,
    description: "Powerful pain relief and fever reducer with optizorb technology.",
    benefits: ["Quick absorption", "Headache relief", "Gentle on stomach"],
  },
  {
    id: "paracetamol",
    name: "Paracetamol 500mg",
    brand: "Cipla",
    category: "Medicines",
    price: 18,
    mrp: 22,
    rating: 4.6,
    reviews: 645,
    image: tabletsImg,
    description: "Standard paracetamol for everyday fever and pain management.",
    benefits: ["Affordable", "Reliable", "Widely trusted"],
  },
  {
    id: "vitamin-d3",
    name: "Vitamin D3 60K Capsules",
    brand: "HealthVit",
    category: "Health Supplements",
    price: 199,
    mrp: 299,
    rating: 4.9,
    reviews: 2104,
    image: vitaminImg,
    badge: "Best Seller",
    description: "Supports bone health, immunity and mood. 10 soft gel capsules.",
    benefits: ["Bone strength", "Immunity boost", "Mood support"],
  },
  {
    id: "multivitamin",
    name: "Multivitamin Gummies",
    brand: "Wellbeing",
    category: "Health Supplements",
    price: 549,
    mrp: 799,
    rating: 4.7,
    reviews: 1532,
    image: multivitaminImg,
    badge: "New",
    description: "Delicious daily gummies with 11 essential vitamins and minerals.",
    benefits: ["Tasty", "Sugar-free", "Daily energy"],
  },
  {
    id: "cough-syrup",
    name: "Benadryl Cough Syrup",
    brand: "J&J",
    category: "Medicines",
    price: 119,
    mrp: 135,
    rating: 4.5,
    reviews: 421,
    image: coughImg,
    description: "Soothing relief from dry and wet cough, 100ml bottle.",
    benefits: ["Fast relief", "Pleasant taste", "Kid-friendly"],
  },
  {
    id: "facewash",
    name: "Vitamin C Brightening Face Wash",
    brand: "Glow&Co",
    category: "Cosmetics",
    price: 349,
    mrp: 499,
    rating: 4.8,
    reviews: 1845,
    image: facewashImg,
    badge: "-30%",
    description: "Gentle daily cleanser with vitamin C for radiant, even toned skin.",
    benefits: ["Brightening", "Sulfate-free", "Dermatologist tested"],
  },
  {
    id: "cerave-moisturizing-cream",
    name: "CeraVe Moisturizing Cream",
    brand: "CeraVe",
    category: "Cosmetics",
    price: 85,
    mrp: 120,
    rating: 4.7,
    reviews: 1120,
    image: moisturizerImg,
    description:
      "Rich, non-greasy cream for dry to very dry skin with ceramides and hyaluronic acid.",
    benefits: ["Long-lasting hydration", "Restores skin barrier", "Fragrance-free"],
  },
  {
    id: "cetaphil-gentle-cleanser",
    name: "Cetaphil Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "Cosmetics",
    price: 60,
    mrp: 85,
    rating: 4.6,
    reviews: 940,
    image: facewashImg,
    description: "Mild, soap-free cleanser suitable for all skin types, even sensitive skin.",
    benefits: ["Non-irritating", "Hydrating", "Dermatologist recommended"],
  },
  {
    id: "the-ordinary-niacinamide",
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "Cosmetics",
    price: 120,
    mrp: 149,
    rating: 4.5,
    reviews: 760,
    image: serumImg,
    description: "High-strength niacinamide serum to reduce pores and balance sebum production.",
    benefits: ["Minimizes pores", "Regulates oil", "Lightweight"],
  },
  {
    id: "la-roche-posay-toleriane",
    name: "La Roche-Posay Toleriane Ultra",
    brand: "La Roche-Posay",
    category: "Cosmetics",
    price: 140,
    mrp: 179,
    rating: 4.8,
    reviews: 540,
    image: moisturizerImg,
    description:
      "Ultra-soothing moisturizer for sensitive and reactive skin with minimal ingredients.",
    benefits: ["Soothes irritation", "Hypoallergenic", "Fast calming effect"],
  },
  {
    id: "bioderma-sensibio-h2o",
    name: "Bioderma Sensibio H2O Micellar Water",
    brand: "Bioderma",
    category: "Cosmetics",
    price: 95,
    mrp: 129,
    rating: 4.9,
    reviews: 1330,
    image: facewashImg,
    description:
      "Gentle micellar cleansing water for sensitive skin — removes makeup and impurities without rinsing.",
    benefits: ["No-rinse cleansing", "Soothes skin", "Ideal for sensitive skin"],
  },
  {
    id: "sunscreen",
    name: "Mineral Sunscreen SPF 50",
    brand: "DermaSafe",
    category: "Skincare",
    price: 499,
    mrp: 699,
    rating: 4.9,
    reviews: 2310,
    image: sunscreenImg,
    badge: "Featured",
    description: "Lightweight, non-greasy broad spectrum sunscreen for daily use.",
    benefits: ["Broad spectrum", "No white cast", "Reef safe"],
  },
  {
    id: "moisturizer",
    name: "Hydra Glow Moisturizer",
    brand: "Aqualine",
    category: "Skincare",
    price: 599,
    mrp: 799,
    rating: 4.7,
    reviews: 1209,
    image: moisturizerImg,
    description: "72-hour deep hydration with hyaluronic acid and ceramides.",
    benefits: ["72h hydration", "Plump skin", "Non-comedogenic"],
  },
  {
    id: "lip-balm",
    name: "Rose Tinted Lip Balm",
    brand: "Petal",
    category: "Cosmetics",
    price: 199,
    mrp: 249,
    rating: 4.6,
    reviews: 530,
    image: lipbalmImg,
    description: "Nourishing lip balm with a subtle rose tint and SPF 15.",
    benefits: ["SPF 15", "All-day moisture", "Subtle tint"],
  },
  {
    id: "shampoo",
    name: "Salon Smooth Shampoo",
    brand: "Botaniq",
    category: "Hair Care",
    price: 449,
    mrp: 599,
    rating: 4.7,
    reviews: 768,
    image: shampooImg,
    description: "Sulfate-free smoothing shampoo for frizz-free, salon shiny hair.",
    benefits: ["Anti-frizz", "Salon shine", "Sulfate-free"],
  },
  {
    id: "hair-oil",
    name: "Ayurvedic Hair Growth Oil",
    brand: "Veda",
    category: "Ayurvedic Products",
    price: 379,
    mrp: 499,
    rating: 4.8,
    reviews: 1422,
    image: hairoilImg,
    badge: "Ayurvedic",
    description: "Traditional blend of 14 herbs to nourish scalp and boost growth.",
    benefits: ["14 herbs", "Reduces fall", "Cold pressed"],
  },
  {
    id: "face-serum",
    name: "Niacinamide 10% Face Serum",
    brand: "PureLab",
    category: "Skincare",
    price: 699,
    mrp: 999,
    rating: 4.9,
    reviews: 3211,
    image: serumImg,
    badge: "Best Seller",
    description: "Concentrated serum to reduce pores, blemishes and uneven tone.",
    benefits: ["Reduces pores", "Even skin tone", "Lightweight"],
  },
  {
    id: "syrup",
    name: "Iron + Folic Acid Syrup",
    brand: "Cipla",
    category: "Health Supplements",
    price: 159,
    mrp: 199,
    rating: 4.5,
    reviews: 312,
    image: syrupImg,
    description: "Daily supplement for healthy iron and energy levels.",
    benefits: ["Energy boost", "Iron rich", "Gentle on stomach"],
  },
];

export const categories = [
  { name: "Medicines", icon: "💊", tint: "from-sky-100 to-sky-50" },
  { name: "Cosmetics", icon: "💄", tint: "from-pink-100 to-rose-50" },
  { name: "Skincare", icon: "✨", tint: "from-teal-100 to-cyan-50" },
  { name: "Hair Care", icon: "💆", tint: "from-amber-100 to-yellow-50" },
  { name: "Baby Care", icon: "🍼", tint: "from-blue-100 to-indigo-50" },
  { name: "Personal Care", icon: "🧴", tint: "from-purple-100 to-fuchsia-50" },
  { name: "Health Supplements", icon: "🌿", tint: "from-emerald-100 to-green-50" },
  { name: "Diabetes Care", icon: "🩸", tint: "from-red-100 to-rose-50" },
  { name: "Ayurvedic Products", icon: "🌱", tint: "from-lime-100 to-green-50" },
  { name: "Medical Equipment", icon: "🩺", tint: "from-slate-100 to-zinc-50" },
];

export const getProduct = (id: string) => products.find((p) => p.id === id);
